[package]
name = "panther"
version = "0.1.0"
edition = "2021"

[lib]
name = "panther"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.15.1", features = ["abi3-py36", "extension-module"] }
numpy = "0.15"
